### ISSUE TITLE
请问怎么运行

### ISSUE THREAD

**Issue by SeakyLuo** [AlarmClockCrusher/HearthstoneSim#1]
不好意思就草草看了一下，好像没看到含有main之类的py文件，请问要运行哪个文件……然后怎么自定义场面这种呀

**Comment by Vinceli2401** [comment]
您好。
在运行之前，你需要安装python，并安装numpy、pygame、hearthstone等库。
安装之后，解压缩这个zip，并在文件夹中运行GUI.py，您就可以使用模拟器了。
如果需要自定义英雄和卡组的话，在Game.py 54行可以更改英雄，在Hand.py 24行和最后更改卡组。
自定义场面的话可能需要一些特殊的编程，而暂时我无法提供任何帮助，请询问软件开发者以获得更多信息。
