### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by CoolChameleon** [AlarmClockCrusher/HearthstoneSim#3]
我是从营地来的老哥，今天刚看到大佬的项目，感觉非常厉害！
不过在测试的过程中遇到了一些问题：
疑似bug：
1. Teron Gorefiend的亡语召唤的随从好像没有+1/+1
2. 有一次大概在6回合的时候游戏崩溃了……报错信息如下：
```
Traceback (most recent call last):
  File "GUI.py", line 698, in <module>
    GameGUI.run()
  File "GUI.py", line 641, in run
    self.Game.playSpell(subject, target, choice)
  File "F:\Desktop\hearthstone\HearthstoneSimulator\Game.py", line 933, in playSpell
    spell.played(target, choice, mana, positioninHand, comment) #choice用于抉择选项，comment 用于区分是GUI环境下使用还是AI分叉
  File "F:\Desktop\hearthstone\HearthstoneSimulator\CardTypes.py", line 1425, in played
    target = self.whenEffective(target, comment, choice, posinHand)
  File "F:\Desktop\hearthstone\HearthstoneSimulator\Classic.py", line 3960, in whenEffective
    copiedMinion = np.random.choice(minions).selfCopy(self.ID)
  File "F:\Desktop\hearthstone\HearthstoneSimulator\CardTypes.py", line 1146, in selfCopy
    Copy.__dict__[key] = copyListDict(value, Copy)
  File "F:\Desktop\hearthstone\HearthstoneSimulator\CardTypes.py", line 26, in copyListDict
    objCopy.append(copy.deepcopy(element))
  File "D:\Anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\lib\copy.py", line 247, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))
  File "D:\Anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda3\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle pygame.Surface objects
```
3. 复生的随从应该在原位置重新召唤
4. 突袭随从在没有可攻击目标之后仍然显示绿色
5. RotnestDrake在没有可消灭目标的情况下，即使手牌有龙似乎也应该是绿色而不是黄色的
6. 发现一个惊天大bug！换完牌之后先手就不抽牌了……
7. 恶魔变形后的英雄技能第二次使用结束造成游戏闪退，报错信息如下：
```
Traceback (most recent call last):
  File "GUI.py", line 698, in <module>
    GameGUI.run()
  File "GUI.py", line 683, in run
    subject.use(item[1]) #Request to use the Hero Power, and its validity is decided later.
  File "F:\Desktop\hearthstone\HearthstoneSimulator\CardTypes.py", line 1729, in use
    self.Game.sendSignal("HeroUsedAbility", self.ID, self, self.Game.target, self.mana, "", choice)
  File "F:\Desktop\hearthstone\HearthstoneSimulator\Game.py", line 606, in sendSignal
    trigger.trigger(signal, ID, subject, target, number, comment, choice)
  File "F:\Desktop\hearthstone\HearthstoneSimulator\Triggers_Auras.py", line 34, in trigger
    self.effect(signal, ID, subject, target, number, comment)
  File "F:\Desktop\hearthstone\HearthstoneSimulator\Outlands.py", line 563, in effect
    if heroPowerReplaced != None:
NameError: name 'heroPowerReplaced' is not defined
```

然后就是卡牌名全部英文的话不太方便[捂脸] 大部分的卡都不认识，有几个怪我是拍下去之后才知道是什么的……
另外，大佬有考虑过创一个qq群吗，可以让帮助测试的老哥们方便交流。
再次对大佬表示感谢及赞叹！

**Comment by AlarmClockCrusher** [comment]
> 我是从营地来的老哥，今天刚看到大佬的项目，感觉非常厉害！
> 不过在测试的过程中遇到了一些问题：
> 疑似bug：
> 
> 1. Teron Gorefiend的亡语召唤的随从好像没有+1/+1
> 2. 有一次大概在6回合的时候游戏崩溃了……报错信息如下：
> 
> ```
> Traceback (most recent call last):
>   File "GUI.py", line 698, in <module>
>     GameGUI.run()
>   File "GUI.py", line 641, in run
>     self.Game.playSpell(subject, target, choice)
>   File "F:\Desktop\hearthstone\HearthstoneSimulator\Game.py", line 933, in playSpell
>     spell.played(target, choice, mana, positioninHand, comment) #choice用于抉择选项，comment 用于区分是GUI环境下使用还是AI分叉
>   File "F:\Desktop\hearthstone\HearthstoneSimulator\CardTypes.py", line 1425, in played
>     target = self.whenEffective(target, comment, choice, posinHand)
>   File "F:\Desktop\hearthstone\HearthstoneSimulator\Classic.py", line 3960, in whenEffective
>     copiedMinion = np.random.choice(minions).selfCopy(self.ID)
>   File "F:\Desktop\hearthstone\HearthstoneSimulator\CardTypes.py", line 1146, in selfCopy
>     Copy.__dict__[key] = copyListDict(value, Copy)
>   File "F:\Desktop\hearthstone\HearthstoneSimulator\CardTypes.py", line 26, in copyListDict
>     objCopy.append(copy.deepcopy(element))
>   File "D:\Anaconda3\lib\copy.py", line 150, in deepcopy
>     y = copier(x, memo)
>   File "D:\Anaconda3\lib\copy.py", line 247, in _deepcopy_method
>     return type(x)(x.__func__, deepcopy(x.__self__, memo))
>   File "D:\Anaconda3\lib\copy.py", line 180, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "D:\Anaconda3\lib\copy.py", line 280, in _reconstruct
>     state = deepcopy(state, memo)
>   File "D:\Anaconda3\lib\copy.py", line 150, in deepcopy
>     y = copier(x, memo)
>   File "D:\Anaconda3\lib\copy.py", line 240, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "D:\Anaconda3\lib\copy.py", line 180, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "D:\Anaconda3\lib\copy.py", line 280, in _reconstruct
>     state = deepcopy(state, memo)
>   File "D:\Anaconda3\lib\copy.py", line 150, in deepcopy
>     y = copier(x, memo)
>   File "D:\Anaconda3\lib\copy.py", line 240, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "D:\Anaconda3\lib\copy.py", line 180, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "D:\Anaconda3\lib\copy.py", line 280, in _reconstruct
>     state = deepcopy(state, memo)
>   File "D:\Anaconda3\lib\copy.py", line 150, in deepcopy
>     y = copier(x, memo)
>   File "D:\Anaconda3\lib\copy.py", line 240, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "D:\Anaconda3\lib\copy.py", line 169, in deepcopy
>     rv = reductor(4)
> TypeError: can't pickle pygame.Surface objects
> ```
> 
> 1. 复生的随从应该在原位置重新召唤
> 2. 突袭随从在没有可攻击目标之后仍然显示绿色
> 3. RotnestDrake在没有可消灭目标的情况下，即使手牌有龙似乎也应该是绿色而不是黄色的
> 4. 发现一个惊天大bug！换完牌之后先手就不抽牌了……
> 5. 恶魔变形后的英雄技能第二次使用结束造成游戏闪退，报错信息如下：
> 
> ```
> Traceback (most recent call last):
>   File "GUI.py", line 698, in <module>
>     GameGUI.run()
>   File "GUI.py", line 683, in run
>     subject.use(item[1]) #Request to use the Hero Power, and its validity is decided later.
>   File "F:\Desktop\hearthstone\HearthstoneSimulator\CardTypes.py", line 1729, in use
>     self.Game.sendSignal("HeroUsedAbility", self.ID, self, self.Game.target, self.mana, "", choice)
>   File "F:\Desktop\hearthstone\HearthstoneSimulator\Game.py", line 606, in sendSignal
>     trigger.trigger(signal, ID, subject, target, number, comment, choice)
>   File "F:\Desktop\hearthstone\HearthstoneSimulator\Triggers_Auras.py", line 34, in trigger
>     self.effect(signal, ID, subject, target, number, comment)
>   File "F:\Desktop\hearthstone\HearthstoneSimulator\Outlands.py", line 563, in effect
>     if heroPowerReplaced != None:
> NameError: name 'heroPowerReplaced' is not defined
> ```
> 
> 然后就是卡牌名全部英文的话不太方便[捂脸] 大部分的卡都不认识，有几个怪我是拍下去之后才知道是什么的……
> 另外，大佬有考虑过创一个qq群吗，可以让帮助测试的老哥们方便交流。
> 再次对大佬表示感谢及赞叹！

**Comment by AlarmClockCrusher** [comment]
疑似bug
1. 我忘了写+1/+1了，我一会儿补上
2. 你当时是在用牧师对战德鲁伊吗？我从你附的traceback里面看不出问题所在，只知道卡牌复制出了问题
结算问题：
1：复生随从的召唤位置我一直没有认真弄清楚，瞎写的
2. 突袭随从绿色代表它可以攻击但是英雄目标显示不正确，这个可改可不改。你在它被冰冻在情况可以知道它是要回合结束时解冻的
3. 可改可不改吧，颜色显示只是一个辅助
4. 你确定牌库里面还有牌吗？
5. 这个我之前也碰到了应该已经改过来了

**Comment by peter-create** [comment]
求视频
（从营地来
